[install]
safety-prompt = false

[custom.all.summary-stat]
type = "local"
path = "."
ipkg = "summary-stat.ipkg"

[custom.all.summary-stat-tests]
type = "local"
path = "tests"
ipkg = "tests.ipkg"

[custom.all.common-definitions-for-tests]
type = "local"
path = "tests/common"
ipkg = "common.ipkg"
